compressionLevel: mixed

enableGlobalCache: false

enableMirror: false

enableTelemetry: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.6.0.cjs

supportedArchitectures:
  os: [linux, darwin]
  cpu: [x64, arm64]
  libc: [glibc, musl]
